import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { format } from "date-fns";
import { Expense, Settlement, Group, User, Transaction } from "@/types";
import { calculateGroupBalances } from "./calculations";
import { normalizeDate } from "./utils";


interface ReportData {
    group: Group;
    expenses: Expense[];
    settlements: Settlement[];
    members: User[];
    currentUser: User;
    startDate?: Date;
    endDate?: Date;
    openingBalance?: number; // Current user's balance before startDate
}

/**
 * Helper to format the "Paid By" string for reports.
 */
const formatPaidBy = (expense: Expense, members: User[]) => {
    if (expense.paidBy) {
        const member = members.find(m => m.uid === expense.paidBy);
        return member?.displayName || member?.email || expense.paidBy;
    }
    if (expense.contributors) {
        return Object.entries(expense.contributors)
            .filter(([_, amount]) => amount > 0)
            .map(([uid, amount]) => {
                const member = members.find(m => m.uid === uid);
                const name = member?.displayName || member?.email || uid;
                return `${name} Rs.${amount.toLocaleString()}`;
            })
            .join(", ");
    }
    return "Multiple";
};

/**
 * Generates a professional PDF report for a group's expenses and settlements.
 */
export const generatePDFReport = (data: ReportData) => {
    const { group, expenses, settlements, members, currentUser, startDate, endDate, openingBalance = 0 } = data;
    const doc = new jsPDF();
    const now = format(new Date(), "PPpp");
    const dateRange = startDate && endDate
        ? `${format(startDate, "PP")} - ${format(endDate, "PP")}`
        : "Full History";

    // --- Header ---
    doc.setFontSize(22);
    doc.setTextColor(13, 148, 136); // Teal-600
    doc.text("SplitEase - Group Report", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    const generatedByName = currentUser.displayName || currentUser.email || "Unknown User";
    doc.text(`Generated by: ${generatedByName}`, 14, 28);
    doc.text(`Generated on: ${now}`, 14, 33);

    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text(`Group: ${group.name}`, 14, 40);
    doc.text(`Period: ${dateRange}`, 14, 48);

    // --- Financial Standing Summary ---
    doc.setFontSize(12);
    doc.text("Your Financial Summary:", 14, 60);

    // Calculate net position after this period's activity
    const periodBalances = calculateGroupBalances(expenses, settlements, group.members);
    const netChange = periodBalances[currentUser.uid] || 0;
    const closingBalance = openingBalance + netChange;

    autoTable(doc, {
        startY: 65,
        head: [['Opening Balance', 'Period Net Change', 'Closing Balance']],
        body: [[
            `Rs.${openingBalance.toLocaleString()}`,
            `Rs.${netChange.toLocaleString()}`,
            `Rs.${closingBalance.toLocaleString()}`
        ]],
        columnStyles: {
            0: { halign: 'right' },
            1: { halign: 'right' },
            2: { halign: 'right' }
        },
        theme: 'grid',
        headStyles: { fillColor: [13, 148, 136] }
    });

    // --- Expense Table ---
    doc.text("Detailed Expense Audit:", 14, (doc as any).lastAutoTable.finalY + 15);

    const expenseRows = expenses.map(e => [
        format(normalizeDate(e.date), "MMM dd, yyyy"),
        e.description,
        formatPaidBy(e, members),
        e.splitType,
        `Rs.${e.amount.toLocaleString()}`
    ]);

    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 20,
        head: [['Date', 'Description', 'Paid By', 'Split', 'Amount']],
        body: expenseRows,
        columnStyles: {
            4: { halign: 'right' }
        },
        theme: 'striped'
    });

    // --- Settlement Table ---
    if (settlements.length > 0) {
        doc.text("Settlements History:", 14, (doc as any).lastAutoTable.finalY + 15);

        const settlementRows = settlements.map(s => [
            format(normalizeDate(s.date), "MMM dd, yyyy"),
            members.find(m => m.uid === s.fromUser)?.displayName || "Unknown",
            members.find(m => m.uid === s.toUser)?.displayName || "Unknown",
            `Rs.${s.amount.toLocaleString()}`
        ]);

        autoTable(doc, {
            startY: (doc as any).lastAutoTable.finalY + 20,
            head: [['Date', 'From', 'To', 'Amount']],
            body: settlementRows,
            columnStyles: {
                3: { halign: 'right' }
            },
            theme: 'striped',
            headStyles: { fillColor: [245, 158, 11] } // Amber-500
        });
    }

    // --- Footer ---
    const totalPages = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${totalPages} - SplitEase Audit System`, doc.internal.pageSize.width / 2, doc.internal.pageSize.height - 10, { align: "center" });
    }

    doc.save(`SplitEase_${group.name.replace(/\s+/g, '_')}_Report.pdf`);
};

/**
 * Generates a multi-sheet Excel report.
 */
export const generateExcelReport = (data: ReportData) => {
    const { group, expenses, settlements, members, currentUser, startDate, endDate, openingBalance = 0 } = data;
    const wb = XLSX.utils.book_new();

    // Sheet 1: Expense Audit
    const expenseData = expenses.map(e => ({
        Date: format(normalizeDate(e.date), "yyyy-MM-dd"),
        Description: e.description,
        Amount: e.amount,
        PaidBy: formatPaidBy(e, members),
        SplitType: e.splitType,
        Note: e.note || ""
    }));
    const wsExpenses = XLSX.utils.json_to_sheet(expenseData);
    XLSX.utils.book_append_sheet(wb, wsExpenses, "Expense Audit");

    // Sheet 2: Member Summary & Net Position
    const balances = calculateGroupBalances(expenses, settlements, group.members);
    const summaryData = group.members.map(mid => {
        const member = members.find(m => m.uid === mid);
        return {
            Member: member?.displayName || member?.email || mid,
            "Period Net Change": balances[mid] || 0,
            "Opening Balance": mid === currentUser.uid ? openingBalance : "N/A",
            "Closing Balance": mid === currentUser.uid ? (openingBalance + (balances[mid] || 0)) : "N/A"
        };
    });
    const wsSummary = XLSX.utils.json_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(wb, wsSummary, "Net Position Summary");

    // Sheet 3: Settlements
    if (settlements.length > 0) {
        const settlementData = settlements.map(s => ({
            Date: format(normalizeDate(s.date), "yyyy-MM-dd"),
            From: members.find(m => m.uid === s.fromUser)?.displayName || s.fromUser,
            To: members.find(m => m.uid === s.toUser)?.displayName || s.toUser,
            Amount: s.amount
        }));
        const wsSettlements = XLSX.utils.json_to_sheet(settlementData);
        XLSX.utils.book_append_sheet(wb, wsSettlements, "Settlements");
    }

    XLSX.writeFile(wb, `SplitEase_${group.name.replace(/\s+/g, '_')}_Report.xlsx`);
};
