import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { format } from "date-fns";
import { Expense, Settlement, Group, User, Transaction } from "@/types";
import { calculateGroupBalances, simplifyDebts } from "./calculations";
import { normalizeDate } from "./utils";


interface ReportData {
    group: Group;
    expenses: Expense[];
    settlements: Settlement[];
    members: User[];
    currentUser: User;
    startDate?: Date;
    endDate?: Date;
    openingBalance?: number; // Current user's balance before startDate
}

const getMemberName = (uid: string, members: User[]) => {
    const member = members.find(m => m.uid === uid);
    if (!member) return uid;
    return member.displayName || member.username || member.email?.split('@')[0] || "User";
};

/**
 * Helper to format the "Paid By" string for reports.
 */
const formatPaidBy = (expense: Expense, members: User[]) => {
    if (expense.paidBy) {
        return getMemberName(expense.paidBy, members);
    }
    if (expense.contributors) {
        return Object.entries(expense.contributors)
            .filter(([_, amount]) => amount > 0)
            .map(([uid, amount]) => {
                const name = getMemberName(uid, members);
                return `${name} (INR ${amount.toLocaleString()})`;
            })
            .join(", ");
    }
    return "Multiple";
};

/**
 * Generates a professional PDF report for a group's expenses and settlements.
 */
export const generatePDFReport = (data: ReportData) => {
    const { group, expenses, settlements, members, currentUser, startDate, endDate, openingBalance = 0 } = data;
    const doc = new jsPDF();
    const now = format(new Date(), "PPpp");
    const dateRange = startDate && endDate
        ? `${format(startDate, "PP")} - ${format(endDate, "PP")}`
        : "Full History";

    // --- Header ---
    doc.setFontSize(22);
    doc.setTextColor(13, 148, 136); // Teal-600
    doc.text("SplitEase - Group Audit Report", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    const generatedByName = getMemberName(currentUser.uid, members);
    doc.text(`Generated by: ${generatedByName}`, 14, 28);
    doc.text(`Generated on: ${now}`, 14, 33);

    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text(`Group: ${group.name}`, 14, 40);
    doc.text(`Period: ${dateRange}`, 14, 48);

    // --- Financial Standing Summary ---
    doc.setFontSize(12);
    doc.text("Global Financial Summary:", 14, 60);

    const totalGroupSpend = expenses.reduce((sum, e) => sum + e.amount, 0);
    const periodBalances = calculateGroupBalances(expenses, settlements, group.members);
    const netChange = periodBalances[currentUser.uid] || 0;
    const closingBalance = openingBalance + netChange;

    autoTable(doc, {
        startY: 65,
        head: [['Total Group Spend', 'Your Opening Bal', 'Your Net Change', 'Your Final Bal']],
        body: [[
            `INR ${totalGroupSpend.toLocaleString()}`,
            `INR ${openingBalance.toLocaleString()}`,
            `INR ${netChange.toLocaleString()}`,
            `INR ${closingBalance.toLocaleString()}`
        ]],
        columnStyles: {
            0: { halign: 'right' },
            1: { halign: 'right' },
            2: { halign: 'right' },
            3: { halign: 'right' }
        },
        theme: 'grid',
        headStyles: { fillColor: [13, 148, 136], fontStyle: 'bold' },
        styles: { font: 'helvetica', fontSize: 9 }
    });

    // --- Category Breakdown ---
    const categoryMap: Record<string, number> = {};
    expenses.forEach(e => {
        const cat = e.category || "General";
        categoryMap[cat] = (categoryMap[cat] || 0) + e.amount;
    });

    doc.text("Spending by Category:", 14, (doc as any).lastAutoTable.finalY + 15);
    const categoryRows = Object.entries(categoryMap)
        .sort((a, b) => b[1] - a[1])
        .map(([cat, amt]) => [cat, `INR ${amt.toLocaleString()}`, `${((amt / totalGroupSpend) * 100).toFixed(1)}%`]);

    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 20,
        head: [['Category', 'Amount', 'Percentage']],
        body: categoryRows,
        columnStyles: {
            1: { halign: 'right' },
            2: { halign: 'right' }
        },
        theme: 'striped'
    });

    // --- Expense Table ---
    doc.addPage();
    doc.text("Itemized Expense List:", 14, 20);

    const expenseRows = expenses.map(e => [
        format(normalizeDate(e.date), "MMM dd, yyyy"),
        e.description,
        formatPaidBy(e, members),
        e.splitType,
        `INR ${e.amount.toLocaleString()}`
    ]);

    autoTable(doc, {
        startY: 25,
        head: [['Date', 'Description', 'Paid By', 'Split', 'Amount']],
        body: expenseRows,
        columnStyles: {
            4: { halign: 'right' }
        },
        theme: 'striped',
        styles: { font: 'helvetica', fontSize: 9 }
    });

    // --- Suggested Settlement Plan ---
    const transactions = simplifyDebts(periodBalances);
    if (transactions.length > 0) {
        doc.text("Suggested Payment Plan (Who pays who):", 14, (doc as any).lastAutoTable.finalY + 15);

        const planRows = transactions.map(t => [
            getMemberName(t.from, members),
            getMemberName(t.to, members),
            `INR ${t.amount.toLocaleString()}`
        ]);

        autoTable(doc, {
            startY: (doc as any).lastAutoTable.finalY + 20,
            head: [['Payer', 'Receiver', 'Amount']],
            body: planRows,
            columnStyles: {
                2: { halign: 'right' }
            },
            theme: 'grid',
            headStyles: { fillColor: [79, 70, 229], fontStyle: 'bold' },
            styles: { font: 'helvetica', fontSize: 9 }
        });
    }

    // --- Settlement History ---
    if (settlements.length > 0) {
        doc.text("Settlement History (Past Payments):", 14, (doc as any).lastAutoTable.finalY + 15);

        const settlementRows = settlements.map(s => [
            format(normalizeDate(s.date), "MMM dd, yyyy"),
            getMemberName(s.fromUser, members),
            getMemberName(s.toUser, members),
            `INR ${s.amount.toLocaleString()}`
        ]);

        autoTable(doc, {
            startY: (doc as any).lastAutoTable.finalY + 20,
            head: [['Date', 'From', 'To', 'Amount']],
            body: settlementRows,
            columnStyles: {
                3: { halign: 'right' }
            },
            theme: 'striped',
            headStyles: { fillColor: [245, 158, 11], fontStyle: 'bold' },
            styles: { font: 'helvetica', fontSize: 9 }
        });
    }

    // --- Footer ---
    const totalPages = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${totalPages} - SplitEase Financial Summary`, doc.internal.pageSize.width / 2, doc.internal.pageSize.height - 10, { align: "center" });
    }

    doc.save(`SplitEase_${group.name.replace(/\s+/g, '_')}_Report.pdf`);
};

/**
 * Generates a multi-sheet Excel report.
 */
export const generateExcelReport = (data: ReportData) => {
    const { group, expenses, settlements, members, currentUser, startDate, endDate, openingBalance = 0 } = data;
    const wb = XLSX.utils.book_new();

    // Sheet 1: Expense Audit
    const expenseData = expenses.map(e => ({
        Date: format(normalizeDate(e.date), "yyyy-MM-dd"),
        Description: e.description,
        Amount: e.amount,
        Category: e.category || "General",
        PaidBy: formatPaidBy(e, members),
        SplitType: e.splitType,
        Note: e.note || ""
    }));
    const wsExpenses = XLSX.utils.json_to_sheet(expenseData);
    XLSX.utils.book_append_sheet(wb, wsExpenses, "Expense Audit");

    // Sheet 2: Category Summary
    const totalSpent = expenses.reduce((sum, e) => sum + e.amount, 0);
    const categoryMap: Record<string, number> = {};
    expenses.forEach(e => {
        const cat = e.category || "General";
        categoryMap[cat] = (categoryMap[cat] || 0) + e.amount;
    });
    const categoryData = Object.entries(categoryMap).map(([cat, amt]) => ({
        Category: cat,
        Amount: amt,
        Percentage: `${((amt / totalSpent) * 100).toFixed(1)}%`
    }));
    const wsCategory = XLSX.utils.json_to_sheet(categoryData);
    XLSX.utils.book_append_sheet(wb, wsCategory, "Category Summary");

    // Sheet 3: Member Summary & Net Position
    const balances = calculateGroupBalances(expenses, settlements, group.members);
    const summaryData = group.members.map(mid => {
        return {
            Member: getMemberName(mid, members),
            "Period Net Change": balances[mid] || 0,
            "Opening Balance": mid === currentUser.uid ? openingBalance : "N/A",
            "Closing Balance": mid === currentUser.uid ? (openingBalance + (balances[mid] || 0)) : "N/A"
        };
    });
    const wsSummary = XLSX.utils.json_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(wb, wsSummary, "Member Summary");

    // Sheet 4: Payment Plan (Suggested Settlements)
    const transactions = simplifyDebts(balances);
    if (transactions.length > 0) {
        const paymentData = transactions.map(t => ({
            From: getMemberName(t.from, members),
            To: getMemberName(t.to, members),
            Amount: t.amount,
            Instruction: `${getMemberName(t.from, members)} needs to pay ${getMemberName(t.to, members)} INR ${t.amount.toLocaleString()}`
        }));
        const wsPayments = XLSX.utils.json_to_sheet(paymentData);
        XLSX.utils.book_append_sheet(wb, wsPayments, "Final Payment Plan");
    }

    XLSX.writeFile(wb, `SplitEase_${group.name.replace(/\s+/g, '_')}_Detailed_Report.xlsx`);
};
